' Gambas module file

Private $hConn As Connection

Public Sub ConectarDB() As Connection
  

    $hConn = New Connection
    $hConn.Host = "localhost"
    $hConn.Name = "db_tacosRoy"
    $hConn.Login = "root"
    $hConn.Password = "t4a2x0a6"
    $hConn.Type = "mysql"
    $hConn.Port = "3306"
    
    Try $hConn.Open
    If Error Then 
      Message.Error(Error.Text & ", " & Error.Where) 
    Else
      Return $hConn
    Endif
    
    If Error Then
      $hConn = Null
      Message.Info("No se puede conectar a la base de datos")
    Endif
End

Public Sub CerrarConexion()
  
  If $hConn = Null Then Return
  $hConn.Close
  $hConn = Null
  
End
' Gambas module file
