' Gambas module file

Private c_Conn As Connection

Public Sub ConectarDB() As Connection
  

    c_Conn = New Connection
    c_Conn.Host = "localhost"
    c_Conn.Name = "db_tacosRoy"
    c_Conn.Login = "admin"
    c_Conn.Password = "Y9dsMe54!"
    c_Conn.Type = "mysql"
    c_Conn.Port = "3306"
    
    Try c_Conn.Open
    If Error Then 
      Message.Error(Error.Text & ", " & Error.Where) 
    Else
      Return c_Conn
    Endif
    
    If Error Then
      c_Conn = Null
      Message.Info("No se puede conectar a la base de datos")
    Endif
End

Public Sub CerrarConexion()
  
  If c_Conn = Null Then Return
  c_Conn.Close
  c_Conn = Null
  
End
' Gambas module file
