' Gambas module file

Private c_Conn As Connection

Public Sub ConectarDB() As Connection
  
  c_Conn = New Connection
  c_Conn.Type = "mysql"
  c_Conn.Host = "localhost"
  c_Conn.Login = "root"
  c_Conn.Port = "3306"
  c_Conn.Name = "db_tacosroy_" & modVariables.sPrefijoDB
  c_Conn.Password = "t4a2x0a6"
  
  Inc Application.Busy
  Try c_Conn.Open()
  Dec Application.Busy
  
  If Error Then 
    Message.Error(Error.Text & ", " & Error.Where) 
    Return Null
    Me.Close
  Else
    Return c_Conn
    Me.close
  Endif

Catch
  Message(Error.Text)  
  Return Null
  Me.close
End

Public Sub CerrarConexion()
  
  If c_Conn = Null Then Return
  c_Conn.Close
  c_Conn = Null
  
End
' Gambas module file
