' Gambas module file

  
'Variables genéricas
Public $hConn As Connection
Public $hResult As Result

Public $usuarioConectado As Integer

'Usuarios
Public idUserGrid As Integer

'Variables para guardar productos
Public $hProductos As Result
Public $currRecordProducto As Result
Public $currProductoInteger As Integer
Public $currCategoriaInteger As Integer

Public $hProductosVenta As Result
Public $currRecordProductoVenta As Result
Public $currProductoIntegerVenta As Integer

Public $ventaSubTotal As Float

Public $ticketNumber As Integer
Public $intTicketNR As Integer
Public $intOrdenID As Integer
Public $strMesaTemp As String
Public $intMesero As Integer
Public $idCategoriaTemp As Integer

Public $intProductoTmp As String
Public $intCantidadProd As String

Public $iLast As Integer
Public sTime As String

Public $FsAMProdsReturn As Boolean
Public $FsAMProdsAction As String

Public $usrAutorizado As Boolean

Public _cnnFechaInicio As Date
Public _cnnFechaFinal As Date

Public $CatCombos As Integer

Public $intTipoPrecio As Integer

Public $bolHabilitado As Boolean
Public $idControlFecha As Integer
Public $controlString As String

Public iDomicilio As Boolean
Public iClienteID As Integer
Public $gridClientes As Result
